# Feladat 3 (2 pont)

Egy kínai cégnél elővigyázatosságból minden nap megmérik a dolgozók testhőmérsékletét. Az így készült mérési adatokat tartalmazza a `testhomerseklet.csv` fájl táblázata április első 20 napjára. (A cég alkalmazottai hétvégén is dolgoznak, kárpótlásul évente 2 hónapra kollektív szabadságot kapnak.) A dolgozókat az `ID` oszlop azonosítja, a mérés időpontja a `dátum` oszlopban, a mért testhőmérséklet °C-ban a `testhőmérséklet` oszlopban található, a `gyanús` oszlop pedig azt jelzi, hogy az adott mérési eredmény ad-e aggodalomra okot. Ezt a testhőmérsékleteket könyvelő titkárnő jegyzi le, a 37,6 °C-nál magasabb hőmérsékletekhez automatikusan "NA"-t (a "NA, nem jól van ez így!" felkiáltást rövidítve) ír, a többit pedig üresen hagyja.

A dolgozókra vonatkozó általános adatokat a `meta.xlsx` Excel fájl táblázatában találjuk. Az `ID` oszlop itt is a dolgozó egyedi azonosítóját tartalmazza, a `nem` és az `életkor` oszlopok értelemszerűen a nemüket és korukat, a `csoport` oszlopban szerepel, hogy az adott dolgozó a cég melyik osztályán dolgozik, az `emelet` oszlopban pedig, hogy az épület hanyadik emeletén.

**Az alábbi feladatokat mind a notebookon belül hajtsuk végre, az eredeti fájlok tartalmát ne változtassuk meg!**

1. Olvassuk be a `meta.xlsx` Excel fájlt egy pandas adattáblába! Sajnos a táblázatba belekerült néhány elírás is, ellenőrizzük, hogy a `nem` oszlop értéke tényleg csak kétféle-e és ha nem, javítsuk ki az elgépeléseket. Hasonlóan ellenőrizzük, hogy az `emelet` oszlopba tényleg az adott munkacsoporthoz tartozó emelet került-e és ha nem, javítsuk ki az alábbi táblázat segítségével:

| munkacsoport       | emelet |
|--------------------|--------|
| menedzsment        | 5      |
| kutatás-fejlesztés | 4      |
| IT                 | 3      |
| takarítók          | 2      |

2. Olvassuk be a `testhomerseklet.csv` fájlt egy másik pandas adattáblába! (Érdemes lehet a fájl szerkezetére rápillantani, hogy könnyebb legyen a beolvasáshoz szükséges beállításokat meghatározni.) A táblázatban a `"--"` string vagy üres cella jelzi a hiányzó adatokat, a `"NA"` pedig a gyanúsnak vélt eseteket. A `dátum` oszlop értékeit mindenképpen dátumként és ne egyszerű string-ként olvassuk be. 
3. Ellenőrizzük, hogy a gyanús eseteket könyvelő titkárnő nem nézett-e el egy-két esetet és ha igen, javítsuk ki a hibát! Hány százalékban téved a titkárnő?
4. Általában a hét napjai közül melyiken van a legtöbb hiányzó hőmérséklet adat?
5. Ábrázoljuk a naponta mért átlagos testhőmérsékleteket az idő függvényében. A napi $\pm$ egy szórásnyi bizonytalanságot jelenítsük meg a átlagot jelző vonal mögött egy halványabb színű, tömör sávval. A gyanús tartomány határát jelezze egy vízszintes, szaggatott, piros vonal.
6. Készítsünk el egy ábrát, melynek 
    - egymás alatti subplotjain munkacsoportonként külön-külön az összes alkalmazott testhőmérsékletének időfüggését ábrázoljuk (tehát nem az átlagukat, hanem egyesével a dolgozókét) mérési pontokkal (nem összekötött vonallal!).
    - A munkacsoportonkénti átlagot egy halványabb, összekötött vonallal ábrázoljuk.
    - Az átlagtól való $\pm$ egy szórásnyi eltérést az adott munkacsoportra itt is egy halványabb színű sáv jelezze,
    - a gyanús tartomány határát pedig egy vízszintes, szaggatott, piros vonal. 
    - Figyeljünk rá, hogy az összes subplot függőleges tengelyén ugyanazt a hőmérséklet-intervallumot ábrázoljuk, hogy az eredmények összevethetőek legyenek!
    - Minden subplotnak legyenek megfelelő tengelyfeliratai (a dátumot elég a legalsó subploton feliratozni) és legyen egyértelmű, hogy melyik munkacsoport adatait ábrázolja!
7. Melyik emeletre lenne a legkisebb kedved felmenni?

In [1]:
import pandas as pd
%pylab inline

Populating the interactive namespace from numpy and matplotlib

In [4]:
df = pd.read_csv("testhomerseklet.csv")

df

,# Ez egy tabulátorokkal elválasztott táblázat,melyben a cég alkalmazottainak
0,# napi testhőmérséklet adatai találhatóak °C m...,NaN
1,ID\tdátum\ttesthőmérséklet\tgyanús,NaN
2,5\t2020-04-01\t37,1\t
3,3\t2020-04-01\t--\t,NaN
4,29\t2020-04-01\t36,8\tNA
5,0\t2020-04-01\t36,9\t
6,21\t2020-04-01\t36,8\tNA
7,4\t2020-04-01\t36,9\t
8,8\t2020-04-01\t37,1\t
9,20\t2020-04-01\t36,7\t
10,28\t2020-04-01\t37,1\t
11,22\t2020-04-01\t37,1\t
12,27\t2020-04-01\t37,1\t
13,7\t2020-04-01\t37,1\tNA
14,14\t2020-04-01\t37,1\t
15,10\t2020-04-01\t37,0\t
16,9\t2020-04-01\t36,9\t
17,25\t2020-04-01\t36,6\t
18,16\t2020-04-01\t36,8\t
19,24\t2020-04-01\t--\t,NaN
20,17\t2020-04-01\t36,9\t
21,12\t2020-04-01\t37,0\t
22,11\t2020-04-01\t36,9\t
23,23\t2020-04-01\t36,8\t
24,6\t2020-04-01\t37,0\tNA
25,2\t2020-04-01\t36,5\t
26,13\t2020-04-01\t37,5\t
27,18\t2020-04-01\t36,9\t
28,26\t2020-04-01\t37,4\tNA
29,15\t2020-04-01\t--\t,NaN
...,...,...
572,24\t2020-04-20\t36,9\t
573,5\t2020-04-20\t36,9\t
574,20\t2020-04-20\t36,9\t
575,8\t2020-04-20\t36,9\tNA
576,4\t2020-04-20\t--\t,NaN
577,12\t2020-04-20\t--\t,NaN
578,26\t2020-04-20\t39,9\tNA
579,9\t2020-04-20\t36,9\t
580,18\t2020-04-20\t36,7\t
581,27\t2020-04-20\t36,9\t
582,17\t2020-04-20\t37,0\t
583,7\t2020-04-20\t39,4\tNA
584,10\t2020-04-20\t36,9\t
585,6\t2020-04-20\t37,4\t
586,0\t2020-04-20\t37,6\t
587,1\t2020-04-20\t37,3\t
588,15\t2020-04-20\t36,7\t
589,25\t2020-04-20\t37,1\t
590,14\t2020-04-20\t--\t,NaN
591,16\t2020-04-20\t--\t,NaN
592,28\t2020-04-20\t36,9\t
593,11\t2020-04-20\t37,3\t
594,3\t2020-04-20\t39,7\tNA
595,13\t2020-04-20\t--\t,NaN
596,21\t2020-04-20\t37,1\t
597,22\t2020-04-20\t39,7\tNA
598,29\t2020-04-20\t--\t,NaN
599,23\t2020-04-20\t36,7\t
600,2\t2020-04-20\t36,8\t
601,19\t2020-04-20\t36,5\t